# Makefile template for SYCL+MPI NAMD/LJ profile (MAXATOMS=256)
# Makefile for CoMD-SYCL-MPI

SHELL = /bin/bash

DOUBLE_PRECISION = ON
DO_MPI           = ON
MAXATOMS         = 256
DEBUG            = OFF

DPCPP_HOME ?= $(HOME)/dpcpp-cuda
CXX        = $(DPCPP_HOME)/bin/clang++

MPI_HOME ?= /usr
CC       ?= $(MPI_HOME)/bin/mpicc

SYCL_FLAGS = -fsycl -fsycl-targets=nvptx64-nvidia-cuda

COMMON_DEFS = -DMAXATOMS=$(MAXATOMS)

ifeq ($(DOUBLE_PRECISION), ON)
COMMON_DEFS += -DCOMD_DOUBLE
else
COMMON_DEFS += -DCOMD_SINGLE
endif

ifeq ($(DO_MPI), ON)
COMMON_DEFS += -DDO_MPI
endif

ifeq ($(DEBUG), ON)
COMMON_DEFS += -DDEBUG -O0 -g
C_OPT   = -O0 -g
CXX_OPT = -O0 -g
else
COMMON_DEFS += -DNDEBUG
C_OPT   = -g -O3
CXX_OPT = -g -O2
endif

CFLAGS   = -std=c99 -Wno-unused-result $(C_OPT) $(COMMON_DEFS)
CXXFLAGS = $(SYCL_FLAGS) $(CXX_OPT) $(COMMON_DEFS) -w

C_INCLUDES   = -I. -I$(MPI_HOME)/include
CXX_INCLUDES = -I. -Iinclude -I$(MPI_HOME)/include

LDFLAGS  = $(SYCL_FLAGS)
ifeq ($(DO_MPI), ON)
LDFLAGS += -L$(MPI_HOME)/lib -lmpi
endif
LDFLAGS += -lm -lstdc++

C_SOURCES = cmdLineParser.c decomposition.c hashTable.c \
            mycommand.c mytype.c \
            performanceTimers.c random.c yamlOutput.c

CXX_C_SOURCES = initAtoms.c ljForce.c neighborList.c

CXX_SOURCES = CoMD.c.dp.cpp eam.c.dp.cpp gpu_kernels.dp.cpp \
              gpu_neighborList.c.dp.cpp gpu_utility.c.dp.cpp \
              haloExchange.c.dp.cpp linkCells.c.dp.cpp timestep.c.dp.cpp \
              parallel.cpp

C_OBJECTS     = $(C_SOURCES:.c=.o)
CXX_C_OBJECTS = $(CXX_C_SOURCES:.c=.o)

CXX_OBJECTS = $(patsubst %.c.dp.cpp,%.c.dp.o,$(filter %.c.dp.cpp,$(CXX_SOURCES))) \
              $(patsubst %.dp.cpp,%.dp.o,$(filter %.dp.cpp,$(filter-out %.c.dp.cpp,$(CXX_SOURCES)))) \
              $(patsubst %.cpp,%.o,$(filter-out %.dp.cpp,$(CXX_SOURCES)))

ALL_OBJECTS = $(C_OBJECTS) $(CXX_C_OBJECTS) $(CXX_OBJECTS)

BIN_DIR = ../bin
ifeq ($(DO_MPI), ON)
CoMD_VARIANT = CoMD-sycl-mpi-namd
else
CoMD_VARIANT = CoMD-sycl-namd
endif
CoMD_EXE = $(BIN_DIR)/$(CoMD_VARIANT)

.SUFFIXES:
.SUFFIXES: .c .cpp .dp.cpp .o

.PHONY: DEFAULT clean distclean

DEFAULT: $(CoMD_EXE)

initAtoms.o: initAtoms.c
	$(CXX) $(CXXFLAGS) $(CXX_INCLUDES) -c $< -o $@

ljForce.o: ljForce.c
	$(CXX) $(CXXFLAGS) $(CXX_INCLUDES) -c $< -o $@

neighborList.o: neighborList.c
	$(CXX) $(CXXFLAGS) $(CXX_INCLUDES) -c $< -o $@

%.o: %.c
	$(CC) $(CFLAGS) $(C_INCLUDES) -c $< -o $@

%.c.dp.o: %.c.dp.cpp
	$(CXX) $(CXXFLAGS) $(CXX_INCLUDES) -c $< -o $@

%.dp.o: %.dp.cpp
	$(CXX) $(CXXFLAGS) $(CXX_INCLUDES) -c $< -o $@

parallel.o: parallel.cpp
	$(CXX) $(CXXFLAGS) $(CXX_INCLUDES) -c $< -o $@

$(CoMD_EXE): $(BIN_DIR) CoMD_info.h $(ALL_OBJECTS)
	$(CXX) -o $(CoMD_EXE) $(ALL_OBJECTS) $(LDFLAGS)

CoMD_info.h: Makefile.NAMD
	./generate_info_header $(CoMD_VARIANT) "$(CXX)" "$(CXXFLAGS)" "$(LDFLAGS)"

$(BIN_DIR):
	@if [ ! -d $(BIN_DIR) ]; then mkdir -p $(BIN_DIR) ; fi

clean:
	rm -f *.o CoMD_info.h .depend

distclean: clean
	rm -f $(CoMD_EXE) .depend.bak
	rm -rf html latex
